# Generated by Django 3.0 on 2020-05-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
