# Generated by Django 3.0 on 2020-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20200506_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_text',
            field=models.CharField(choices=[('BestSeller', 'bestseller'), ('New', 'new')], default='new', max_length=20),
            preserve_default=False,
        ),
    ]
