# Generated by Django 3.0 on 2020-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_item_label_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_text',
            field=models.CharField(choices=[('BestSeller', 'Bestseller'), ('New', 'New')], max_length=20),
        ),
    ]
